// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpUGO0O_NLta3cxyJcTqoQ3Q7z2iPeb4',
    appId: '1:747458844179:web:60b74971e99dc7c4a051e6',
    messagingSenderId: '747458844179',
    projectId: 'flutterfilmleruygulamasi',
    authDomain: 'flutterfilmleruygulamasi.firebaseapp.com',
    storageBucket: 'flutterfilmleruygulamasi.appspot.com',
    measurementId: 'G-CK81YB9T6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3yrJWaOvwyt3R7Zi3wSwqCo_2o8Cubk',
    appId: '1:747458844179:android:9b0f4177f6e5ed5ca051e6',
    messagingSenderId: '747458844179',
    projectId: 'flutterfilmleruygulamasi',
    storageBucket: 'flutterfilmleruygulamasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLtWucqHnDZORsv1wjnIR1934ZfzUqAhk',
    appId: '1:747458844179:ios:b273f7ccb405050ca051e6',
    messagingSenderId: '747458844179',
    projectId: 'flutterfilmleruygulamasi',
    storageBucket: 'flutterfilmleruygulamasi.appspot.com',
    iosBundleId: 'com.example.flutterfilmleruygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLtWucqHnDZORsv1wjnIR1934ZfzUqAhk',
    appId: '1:747458844179:ios:b273f7ccb405050ca051e6',
    messagingSenderId: '747458844179',
    projectId: 'flutterfilmleruygulamasi',
    storageBucket: 'flutterfilmleruygulamasi.appspot.com',
    iosBundleId: 'com.example.flutterfilmleruygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCpUGO0O_NLta3cxyJcTqoQ3Q7z2iPeb4',
    appId: '1:747458844179:web:76d5f73728fde93ea051e6',
    messagingSenderId: '747458844179',
    projectId: 'flutterfilmleruygulamasi',
    authDomain: 'flutterfilmleruygulamasi.firebaseapp.com',
    storageBucket: 'flutterfilmleruygulamasi.appspot.com',
    measurementId: 'G-JZ50NNP488',
  );
}
